name: HTMLCheck
on:
  push:
    branches: [main]

jobs:
  TestHtml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/ckeckout@v2
      - name: Check HTML Syntax
        run: npx prettier *.html
